name: Testing

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: deps
      run: make deps

    - name: run lint
      run: make lint

    - name: run tests
      run: make test
